server:
  port: 80
spring:
  application:
    name: business-gateway
  cloud:
    gateway:
      routes:
      - id: web_route
        order: 100
        uri: http://localhost:8000
        predicates:
        - Path= /**
      - id: business-analysis-webfd
        uri: lb://business-analysis-webfd
        predicates:
        - Path= /business-analysis-webfd/**
        filters:
        - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://erueka-master.superbio.cn:8100/eureka/,http://erueka-slave.superbio.cn:8101/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.gateway: trace
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"